# Site wide configuration

title: "upcyc.xyz"
description: "Coming Soon!"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author:

#Target date in UTC / GMT
countdown:
  theme: flat-colors-wide
  year: 2016
  month: 2
  day: 1
  hour: 0
  minute: 0

color1: "#FFFBB7"
color2: "#A6F6AF"
color3: "#66B6AB"
color4: "#5B7C8D"
color5: "#4F2958"
theme_num: "84"

# Site owner
owner:
  name: siteCo.xyz
  email: xyzsiteco@gmail.com
  twitter: sitecoxyz
  facebook: sitecoxyz
  google_plus: sitecoxyz
  instagram: sitecoxyz
  url: http://siteco.xyz
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
